
# 文章评分系统
 # widgetpack。将 false 改为 widgetpack 上的 id 则启用该评论系统。
 # Star rating support to each article.
 # To get your ID visit https://widgetpack.com
widgetpack:
  enable: true #false
  id: 30332 #<app_id>
  color:  fc6423

# title
title: xueyisheng

# 来必力评论系统
# livere配置
livere:
  enable: false
  uid: MTAyMC81MzA1OS8yOTUzNQ==

# Twikoo
# 基于腾讯云开发
# Based on Tencent CloudBase
# See: https://twikoo.js.org
twikoo:
  enable: true
  envId: https://www.nothinglintwikoo.ml/

# tawk在线聊天系统
tawk:
  enable: false

# tidio在线聊天系统
tidio:
  enable: false

# Chatra在线聊天系统
chatra:
  enable: true

# 博客brand设置
blogTitle:
  bigtitle: "屹清纪"
  subtitle: "不积跬步无以至千里，后继才能薄发"

# 个人信息介绍栏
aboutAuthor: "XueYisheng的个人简介"
AuthorInfo: "记录不是无效的"

# share
shareHref:
  wechat: https://cdn.staticaly.com/gh/xys176/image-hosting@master/1c91c96cff234821b0335dfd7f08eb5.bx0v5d7rqu8.webp
  public: /img/subscribe.jpg
  zhihu: https://cdn.staticaly.com/gh/xys176/image-hosting@master/efd46100b0856d0667e71e2c551fd3c.1ycidoix7iv4.webp
  jianshu: https://cdn.staticaly.com/gh/xys176/image-hosting@master/4f0c57dd10011aab86679f60befc591.1boqi7yl8xr4.webp
  github: https://github.com/xys176
  weibo:
  rss:

## Feed
rss: /atom.xml
## favicon
favicon: /img/avatar.jpg

# 文章日历
# Whether to display post-calender in the `archive` page
# 设置在归档页面achive中是否显示'文章日历'控件
# 仿GitHub贡献条
postCalendar: true
js:
  echarts: https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/echarts.min.js
